---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: demo
spec:
  releaseName: cert-manager
  interval: 1m
  sourceRef:
    kind: HelmRepository
    name: cert-manager
    namespace: flux-system
    version: >=1.1.0
  values:
    image:
      repository: quay.io/jetstack/cert-manager-controller
      tag: canary
    rbac:
      create: true
