---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~v1.1.0
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: jetstack/cert-manager
    version: v1.1.0
  values:
    image:
      repository: quay.io/jetstack/cert-manager-controller
      tag: canary
    tag: 4
    rbac:
      create: true
